#ifndef COLLECTION_H
#define COLLECTION_H

/**
 * @brief The collection ID to query measurement values from
 */
typedef enum COL_ID {
    AC_MEASUREMENT = 10,
    HARMONIC_ANALYSIS_L1 = 20,
    HARMONIC_ANALYSIS_L2 = 21,
    HARMONIC_ANALYSIS_L3 = 22
} COL_ID;

/**
 * @brief The measurement collection for the AC measurement
 */
typedef enum MET_ID_AC {
    VOLTAGE_RMS_L1N = 4,
    VOLTAGE_RMS_L2N = 5,
    VOLTAGE_RMS_L3N = 6,
    VOLTAGE_RMS_MAX_L1N = 43,
    VOLTAGE_RMS_MAX_L2N = 44,
    VOLTAGE_RMS_MAX_L3N = 45,
    VOLTAGE_RMS_MIN_L1N = 46,
    VOLTAGE_RMS_MIN_L2N = 47,
    VOLTAGE_RMS_MIN_L3N = 48,
    VOLTAGE_RMS_L1L2 = 31,
    VOLTAGE_RMS_L1L3 = 32,
    VOLTAGE_RMS_L2L2 = 33,
    VOLTAGE_MEAN_L1N = 49,
    VOLTAGE_MEAN_L2N = 50,
    VOLTAGE_MEAN_L3N = 51,
    VOLTAGE_PEAK_L1N = 91,
    VOLTAGE_PEAK_L2N = 92,
    VOLTAGE_PEAK_L3N = 93,

    CURRENT_RMS_L1 = 1,
    CURRENT_RMS_L2 = 2,
    CURRENT_RMS_L3 = 3,
    CURRENT_RMS_MAX_L1 = 34,
    CURRENT_RMS_MAX_L2 = 35,
    CURRENT_RMS_MAX_L3 = 36,
    CURRENT_RMS_MIN_L1 = 37,
    CURRENT_RMS_MIN_L2 = 38,
    CURRENT_RMS_MIN_L3 = 39,
    CURRENT_MEAN_L1 = 40,
    CURRENT_MEAN_L2 = 41,
    CURRENT_MEAN_L3 = 42,
    CURRENT_PEAK_L1 = 94,
    CURRENT_PEAK_L2 = 95,
    CURRENT_PEAK_L3 = 96,
    CURRENT_RMS_N = 97,

    POWER_EFFECTIVE_L1 = 7,
    POWER_EFFECTIVE_L2 = 8,
    POWER_EFFECTIVE_L3 = 9,
    POWER_EFFECTIVE_MAX_L1 = 52,
    POWER_EFFECTIVE_MAX_L2 = 53,
    POWER_EFFECTIVE_MAX_L3 = 54,
    POWER_EFFECTIVE_MIN_L1 = 55,
    POWER_EFFECTIVE_MIN_L2 = 56,
    POWER_EFFECTIVE_MIN_L3 = 57,
    POWER_REACTIVE_L1 = 10,
    POWER_REACTIVE_L2 = 11,
    POWER_REACTIVE_L3 = 12,
    POWER_APPARENT_L1 = 13,
    POWER_APPARENT_L2 = 14,
    POWER_APPARENT_L3 = 15,

    ENERGY_ACTIVE_L1 = 64,
    ENERGY_ACTIVE_L2 = 65,
    ENERGY_ACTIVE_L3 = 66,
    ENERGY_ACTIVE_IMPORT_L1 = 67,
    ENERGY_ACTIVE_IMPORT_L2 = 68,
    ENERGY_ACTIVE_IMPORT_L3 = 69,
    ENERGY_ACTIVE_EXPORT_L1 = 70,
    ENERGY_ACTIVE_EXPORT_L2 = 71,
    ENERGY_ACTIVE_EXPORT_L3 = 72,
    ENERGY_ACTIVE_TOTAL = 73,
    ENERGY_ACTIVE_IMPORT_TOTAL = 74,
    ENERGY_ACTIVE_EXPORT_TOTAL = 75,
    ENERGY_REACTIVE_L1 = 76,
    ENERGY_REACTIVE_L2 = 77,
    ENERGY_REACTIVE_L3 = 78,
    ENERGY_REACTIVE_INDUCTIVE_L1 = 79,
    ENERGY_REACTIVE_INDUCTIVE_L2 = 80,
    ENERGY_REACTIVE_INDUCTIVE_L3 = 81,
    ENERGY_REACTIVE_CAPACITIVE_L1 = 82,
    ENERGY_REACTIVE_CAPACITIVE_L2 = 83,
    ENERGY_REACTIVE_CAPACITIVE_L3 = 84,
    ENERGY_REACTIVE_TOTAL = 85,
    ENERGY_REACTIVE_TOTAL_INDUCTIVE = 86,
    ENERGY_REACTIVE_TOTAL_CAPACITIVE = 87,
    ENERGY_APPARENT_L1 = 88,
    ENERGY_APPARENT_L2 = 89,
    ENERGY_APPARENT_L3 = 90,
    
    LINE_FREQUENCY_L1 = 16,
    LINE_FREQUENCY_L2 = 17,
    LINE_FREQUENCY_L3 = 18,
    LINE_FREQUENCY_MAX_L1 = 58,
    LINE_FREQUENCY_MAX_L2 = 59,
    LINE_FREQUENCY_MAX_L3 = 60,
    LINE_FREQUENCY_MIN_L1 = 61,
    LINE_FREQUENCY_MIN_L2 = 62,
    LINE_FREQUENCY_MIN_L3 = 63,

    PHASE_ANGLE_PHI_L1 = 19,
    PHASE_ANGLE_PHI_L2 = 20,
    PHASE_ANGLE_PHI_L3 = 21,
    COS_PHI_L1 = 22,
    COS_PHI_L2 = 23,
    COS_PHI_L3 = 24,

    POWER_FACTOR_PF_L1 = 25,
    POWER_FACTOR_PF_L2 = 26,
    POWER_FACTOR_PF_L3 = 27,
    POWER_FACTOR_LF_L1 = 28,
    POWER_FACTOR_LF_L2 = 29,
    POWER_FACTOR_LF_L3 = 30
} MET_ID_AC;

#endif
